# agentstack scheduled job — generated by /agentstack-schedule
# Slug:      {{slug}}
# Runner:    {{name}}
# Schedule:  {{schedule_human}}
# Generated: {{generated_at}}

[Unit]
Description=agentstack scheduled runner — {{slug}}/{{name}}
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
WorkingDirectory={{agency_root}}
ExecStart=/bin/bash {{wrapper_path}}
StandardOutput=append:{{log_path}}
StandardError=append:{{log_path}}
# systemd-run-as-user inherits a minimal env; the wrapper sources .env itself,
# but we still need PATH so the wrapper can find pnpm.
Environment=PATH=/usr/local/bin:/usr/bin:/bin
Nice=10
