# agentstack scheduled timer — generated by /agentstack-schedule
# Slug:      {{slug}}
# Runner:    {{name}}
# Schedule:  {{schedule_human}}
# Generated: {{generated_at}}

[Unit]
Description=agentstack scheduled timer — {{slug}}/{{name}}

[Timer]
{{schedule_block}}
# Persistent=true means: if the system was off when a tick should have fired,
# fire once on next boot. Matches launchd's "missed-fire" semantics.
Persistent=true
Unit={{service_filename}}

[Install]
WantedBy=timers.target
