<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  agentstack scheduled job — generated by /agentstack-schedule
  Slug:      {{slug}}
  Runner:    {{name}}
  Schedule:  {{schedule_human}}
  Generated: {{generated_at}}
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{{label}}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{{wrapper_path}}</string>
    </array>

    <key>WorkingDirectory</key>
    <string>{{agency_root}}</string>

    <!-- One of: StartInterval (seconds) OR StartCalendarInterval (calendar) -->
    {{schedule_block}}

    <key>RunAtLoad</key>
    <false/>

    <key>StandardOutPath</key>
    <string>{{log_path}}</string>

    <key>StandardErrorPath</key>
    <string>{{log_path}}</string>

    {{wake_block}}

    <!-- Cron / launchd contexts have an empty PATH; we need pnpm + node + git
         visible. Adjust if your binaries live elsewhere. -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
</dict>
</plist>
