#!/usr/bin/env bash
# agentstack scheduled wrapper — generated by /agentstack-schedule
# Schedule:    {{schedule_human}}
# Slug:        {{slug}}
# Runner:      {{name}}
# Target:      {{target_script}}
# Generated:   {{generated_at}}
#
# This wrapper is what launchd / systemd actually invokes. It does four jobs the
# scheduler can't do for you:
#
#   1. cd into the agency root (cron contexts have no cwd)
#   2. source .env (cron contexts have no shell env)
#   3. enforce a window of operation (e.g. only run 09:00-21:00)
#   4. hold a lock so a slow run never overlaps with the next tick
#
# Edit the schedule by editing the plist/service file, not this wrapper.

set -uo pipefail

# ─── Paths (substituted at generation time) ────────────────────────
AGENCY_ROOT="{{agency_root}}"
LOG_FILE="{{log_path}}"
LOCK_FILE="{{lock_path}}"
TARGET_SCRIPT="{{target_script}}"

# ─── Window of operation (no-op if always-on) ──────────────────────
WINDOW_START="{{window_start}}"   # hour 0-23, or "" for always
WINDOW_END="{{window_end}}"       # hour 0-23, or "" for always

if [ -n "$WINDOW_START" ] && [ -n "$WINDOW_END" ]; then
  HOUR=$(date +%H)
  HOUR=${HOUR#0}                  # strip leading zero so "09" → "9"
  HOUR=${HOUR:-0}                 # handle "00" → ""
  if [ "$HOUR" -lt "$WINDOW_START" ] || [ "$HOUR" -ge "$WINDOW_END" ]; then
    exit 0
  fi
fi

# ─── Working directory ─────────────────────────────────────────────
cd "$AGENCY_ROOT" || {
  echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] FATAL: agency root missing: $AGENCY_ROOT" >&2
  exit 1
}

# ─── Load .env so the script has API keys / DB URLs ────────────────
if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  . .env
  set +a
fi

# ─── Logging ───────────────────────────────────────────────────────
mkdir -p "$(dirname "$LOG_FILE")"
ts() { date -u '+%Y-%m-%dT%H:%M:%SZ'; }
log() { echo "[$(ts)] $*" >> "$LOG_FILE"; }

# ─── Lock — skip if previous run still going ───────────────────────
mkdir -p "$(dirname "$LOCK_FILE")"
exec 9>"$LOCK_FILE"
if ! flock -n 9; then
  log "skip: previous run still holds the lock"
  exit 0
fi

# ─── Run ───────────────────────────────────────────────────────────
log "start: $TARGET_SCRIPT"
START_NS=$(date +%s)
if pnpm tsx "$TARGET_SCRIPT" >> "$LOG_FILE" 2>&1; then
  log "ok ($(($(date +%s) - START_NS))s)"
else
  STATUS=$?
  log "FAIL exit=$STATUS ($(($(date +%s) - START_NS))s)"
  exit "$STATUS"
fi
